baseURL = 'https://livres-startup.fr'
title = 'Livres Startup - Des livres pour entreprendre'
theme = 'mainroad'
googleAnalytics = "G-C7WWBF4CTC"
defaultContentLanguage = "fr"
enableRobotsTXT = true

[taxonomies]
  author = "auteurs"
  tag = "tags"
  category = "categories"

[Params.logo]
  image = "/img/logo.png"
  title = "Livres Startup"
  subtitle = "Les bonnes lectures pour entreprendre"

[Params.favicon]
  image = "/img/favicon.png"

[Params]
  description = "Besoin de conseils pour lancer votre entreprise ? Découvrez notre sélection de livres sur les startups et l'entrepreneuriat, qui couvrent toutes les étapes de la création d'une entreprise et vous aideront à réussir." # Site description. Used in meta description
  copyright = "livre-startup.fr" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories"] # Order of post meta information
  mainSections = ["livres"]
  languageCode = "fr-fr"
  dateFormat = "2 January 2006"
  dateFormatFull = "02/01/2006"
  dateFormatTime = "2 Jan 2006 15:04"
  customCSS = ["css/custom.css", "css/googlefont.css"]

[Params.content.filters]
  author = true

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["recent", "categories", "taglist"]
