[[redirects]]
  from = "https://livres-startup.fr/author/richard-thaler.html"
  to = "https://livres-startup.fr/auteurs/richard-thaler.html"
  status = 301
  force = true

[[redirects]]
  from = "https://livres-startup.fr/author/eric-ries.html"
  to = "https://livres-startup.fr/auteurs/eric-ries.html"
  status = 301
  force = true

[[redirects]]
  from = "https://livres-startup.fr/category/motivation-et-leadership.html"
  to = "https://livres-startup.fr/tags/motivation/"
  status = 301
  force = true

[[redirects]]
  from = "https://livres-startup.fr/category/economie.html"
  to = "https://livres-startup.fr/tags/economie-comportementale/"
  status = 301
  force = true